#!/usr/bin/env python3
"""Convert the user's original WAV files without modifying them."""

import array
import hashlib
import json
import math
import subprocess
import sys
import wave
from pathlib import Path

source = Path(sys.argv[1])
out = Path(__file__).parent
names = [
    "menu",
    "menu_navigate",
    "menu_select",
    "backkey",
    "close",
    "setting_applyed",
    "volume_adjust",
    "long press shortcut",
    "battery_low",
    "dnd_off",
    "dialog_failed",
]
parts = [
    "/* Generated by private/key-sounds/prepare.py. Private user-provided audio. */"
]
metadata = []
for name in names:
    c_name = name.replace(" ", "_")
    raw = subprocess.check_output(
        [
            "ffmpeg",
            "-v",
            "error",
            "-i",
            str(source / (name + ".wav")),
            "-ac",
            "1",
            "-ar",
            "16000",
            "-f",
            "s16le",
            "-",
        ]
    )
    a = array.array("h")
    a.frombytes(raw)
    peak = max((abs(x) for x in a), default=0)
    threshold = max(48, peak * 3 // 1000)
    frame = 64
    active = []
    for i in range(0, len(a), frame):
        block = a[i : i + frame]
        rms = math.sqrt(sum(x * x for x in block) / max(1, len(block)))
        if rms >= threshold:
            active.append(i)
    first = active[0] if active else 0
    last = min(len(a), (active[-1] + frame) if active else len(a))
    start = max(0, first - 32)
    end = min(len(a), last + 160)
    a = a[start:end]
    for i in range(min(32, len(a))):
        a[i] = round(a[i] * i / 32)
    fade = min(128, len(a))
    for i in range(fade):
        a[-fade + i] = round(a[-fade + i] * (fade - 1 - i) / (fade - 1))
    with wave.open(str(out / (name + ".wav")), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(16000)
        w.writeframes(a.tobytes())
    parts.append(
        "static const int16_t s_sound_"
        + c_name
        + "[] = {\n"
        + "\n".join(
            ",".join(map(str, a[i : i + 24])) + "," for i in range(0, len(a), 24)
        )
        + "\n};"
    )
    metadata.append(
        {
            "file": name + ".wav",
            "leading_trim_ms": start / 16,
            "trailing_trim_ms": (len(raw) // 2 - end) / 16,
            "samples": len(a),
            "sha256": hashlib.sha256(
                (source / (name + ".wav")).read_bytes()
            ).hexdigest(),
        }
    )
parts.append(
    "static const KeySoundSample s_samples[] = {\n"
    + "".join(
        "{s_sound_" + n.replace(" ", "_") + ", sizeof(s_sound_" + n.replace(" ", "_")
        + ") / sizeof(int16_t)},\n"
        for n in names
    )
    + "};"
)
Path("src/fw/services/speaker/key_sounds_data.inc").write_text("\n".join(parts) + "\n")
(out / "processing.json").write_text(json.dumps(metadata, indent=2) + "\n")
print(json.dumps(metadata, indent=2))
