#!/usr/bin/env python3
"""Convert the user's original WAV files without modifying them."""

import array
import hashlib
import json
import subprocess
import sys
import wave
from pathlib import Path

source = Path(sys.argv[1])
out = Path(__file__).parent
names = [
    "menu",
    "menu_navigate",
    "menu_select",
    "backkey",
    "close",
    "setting_applyed",
    "volume_adjust",
    "battery_low",
    "dnd_off",
]
parts = [
    "/* Generated by private/key-sounds/prepare.py. Private user-provided audio. */"
]
metadata = []
for name in names:
    raw = subprocess.check_output(
        [
            "ffmpeg",
            "-v",
            "error",
            "-i",
            str(source / (name + ".wav")),
            "-ac",
            "1",
            "-ar",
            "16000",
            "-f",
            "s16le",
            "-",
        ]
    )
    a = array.array("h")
    a.frombytes(raw)
    first = next((i for i, x in enumerate(a) if abs(x) > 32), 0)
    trim = max(0, first - 32)
    a = a[trim:]
    for i in range(min(32, len(a))):
        a[i] = round(a[i] * i / 32)
    fade = min(128, len(a))
    for i in range(fade):
        a[-fade + i] = round(a[-fade + i] * (fade - 1 - i) / (fade - 1))
    with wave.open(str(out / (name + ".wav")), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(16000)
        w.writeframes(a.tobytes())
    parts.append(
        "static const int16_t s_sound_"
        + name
        + "[] = {\n"
        + "\n".join(
            ",".join(map(str, a[i : i + 24])) + "," for i in range(0, len(a), 24)
        )
        + "\n};"
    )
    metadata.append(
        {
            "file": name + ".wav",
            "trim_ms": trim / 16,
            "samples": len(a),
            "sha256": hashlib.sha256(
                (source / (name + ".wav")).read_bytes()
            ).hexdigest(),
        }
    )
parts.append(
    "static const KeySoundSample s_samples[] = {\n"
    + "".join(
        "{s_sound_" + n + ", sizeof(s_sound_" + n + ") / sizeof(int16_t)},\n"
        for n in names
    )
    + "};"
)
Path("src/fw/services/speaker/key_sounds_data.inc").write_text("\n".join(parts) + "\n")
(out / "processing.json").write_text(json.dumps(metadata, indent=2) + "\n")
print(json.dumps(metadata, indent=2))
